CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[Username] VARCHAR(100) NOT NULL UNIQUE,
	[Email] VARCHAR(255) NOT NULL UNIQUE,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[TravelProfileId] UNIQUEIDENTIFIER NOT NULL,
	[HostProfileId] UNIQUEIDENTIFIER NOT NULL,

	


	
);